export const ADD_INVOICE = 'ADD_INVOICE';
export const REMOVE_INVOICE = 'REMOVE_INVOICE';
export const UPDATE_INVOICE = 'UPDATE_INVOICE';

export const ADD_DETAILS = 'ADD_DETAILS';
export const UPDATE_DETAILS = 'UPDATE_DETAILS';
export const EDIT_DETAILS = 'EDIT_DETAILS';
export const RESET_DETAILS = 'RESET_DETAILS';

export const SET_INVOICE_TOTAL = 'SET_INVOICE_TOTAL';

export const SET_LOADING = 'SET_LOADING';

export const REHYDRATE_STORE = 'REHYDRATE_STORE';
export const RESET_DATA = 'RESET_DATA';
